version: '2'
services:
    openldap:
        image: dinkel/openldap
        environment:
          - SLAPD_ORGANIZATION=开发者平台
          - SLAPD_DOMAIN=devpt.ltd
          - SLAPD_PASSWORD=toread
        ports:
          - "389:389"
        volumes:
          - /data/docker-storage/openldap-server/config:/etc/ldap
          - /data/docker-storage/openldap-server/data:/var/lib/ldap
    ldap-account-admin:
        build: ./docker-ldap-account-manager
        depends_on:
          - openldap
        ports:
          - "8888:80"
        volumes:
          - /data/docker-storage/lam:/var/lib/ldap-account-manager/config
    postgres:
        image: postgres
        restart: always
        volumes:
          - /data/docker-storage/postgres-data:/var/lib/postgresql/data
          - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        environment:
          POSTGRES_USER:  postgres
          POSTGRES_PASSWORD: toread
    redis:
         image: redis
         volumes:
          - /data/docker-storage/redis-data:/data
    gitlabce:
        image: 'twang2218/gitlab-ce-zh:latest'
        depends_on:
          - redis
          - postgres
          - openldap
        restart: always
        ports:
        - "10080:80"
        - "10022:22"
        volumes:
          - /data/docker-storage/gitlab-config:/etc/gitlab
          - /data/docker-storage/gitlab-logs:/var/log/gitlab
          - /data/docker-storage/gitlab-data:/var/opt/gitlab
    mattermost:
        image: mattermost/mattermost-prod-app:3.9.0
        depends_on:
          - postgres
        environment:
          MATTERMOST_ENABLE_SSL: "true"
          DB_HOST: postgres
          MM_DBNAME: mattermost
          MM_USERNAME: mattermost
          MM_PASSWORD: mattermost
        ports:
          - "30080:80"
        volumes:
          - /data/docker-storage/mattermost-data:/mattermost/data
          - /data/docker-storage/mattermost-config:/mattermost/config

