version: '2'
services:
    nginx:
        build: nginx
        ports:
          - "88:88"
          - "81:80"
        environment:
          REVERSE_PROXY_DOMAIN_NAME: devpt.ltd:88
        depends_on:
          - nexus
          - mattermost
          - gitlabce
          - account
          - sonarqube
          - owncloud
    redis:
         image: redis
         volumes:
          - /data/docker-storage/redis-data:/data
    postgres:
        image: postgres:9.6
        restart: always
        volumes:
          - /data/docker-storage/postgres-data:/var/lib/postgresql/data
          - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        environment:
          POSTGRES_USER:  postgres
          POSTGRES_PASSWORD: toread
    openldap:
        image: dinkel/openldap
        environment:
          - SLAPD_ORGANIZATION=开发者平台
          - SLAPD_DOMAIN=devpt.ltd
          - SLAPD_PASSWORD=toread
        ports:
          - "389:389"
        volumes:
          - /data/docker-storage/openldap-server/config:/etc/ldap
          - /data/docker-storage/openldap-server/data:/var/lib/ldap
    account:
        build: ./docker-ldap-account-manager
        depends_on:
          - openldap
        volumes:
          - /data/docker-storage/lam:/var/lib/ldap-account-manager/config
    gitlabce:
        image: 'twang2218/gitlab-ce-zh:latest'
        depends_on:
          - redis
          - postgres
          - openldap
        restart: always
        volumes:
          - /data/docker-storage/gitlab-config:/etc/gitlab
          - /data/docker-storage/gitlab-logs:/var/log/gitlab
          - /data/docker-storage/gitlab-data:/var/opt/gitlab
    mattermost:
        image: mattermost/mattermost-prod-app:3.9.0
        depends_on:
          - postgres
        environment:
          MATTERMOST_ENABLE_SSL: "true"
          DB_HOST: postgres
          MM_DBNAME: mattermost
          MM_USERNAME: mattermost
          MM_PASSWORD: mattermost
        volumes:
          - /data/docker-storage/mattermost-data:/mattermost/data
          - /data/docker-storage/mattermost-config:/mattermost/config
    nexus:
        image: sonatype/nexus3
        depends_on:
          - openldap
        volumes:
          - /data/docker-storage/nexus-data:/nexus-data
    sonarqube:
        image: sonarqube
        depends_on:
          - postgres
        ports:
          - "192:9092"
        environment:
          - SONARQUBE_JDBC_USERNAME=sonarqube
          - SONARQUBE_JDBC_PASSWORD=sonarqube
          - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
        volumes:
          - /data/docker-storage/sonarqube/conf:/opt/sonarqube/conf
          - /data/docker-storage/sonarqube/data:/opt/sonarqube/data
          - /data/docker-storage/sonarqube/extensions:/opt/sonarqube/extensions
          - /data/docker-storage/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
    owncloud:
      image: owncloud
      depends_on:
        - postgres
      volumes:
        - /data/docker-storage/owncloud/data:/var/www/html/data
        - /data/docker-storage/owncloud/config:/var/www/html/config
        - /data/docker-storage/owncloud/apps:/var/www/html/apps